name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependencies
      run: |
        sudo apt-get install -y \
          build-essential \
          cmake \
          libboost-filesystem-dev \
          libmarisa-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: rime_table_bin_decompiler
        path: ${{github.workspace}}/build/**/rime_table_bin_decompiler
